baseURL = 'https://thegreatwaves.github.io/'
languageCode = 'en-us'
title = 'Portfolio Site'
theme = 'portfolio'
enableGitInfo = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true
